[versions]

paper = "1.21.11-R0.1-SNAPSHOT"

gradle-plugins = "1.6.1"

[libraries]

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]

jcommon = { id = "dev.siroshun.gradle.plugins.jcommon", version.ref = "gradle-plugins" }
bundler = { id = "dev.siroshun.gradle.plugins.bundler", version.ref = "gradle-plugins" }
